

services:
  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"
    volumes:
      - ./cassandra-data:/var/lib/cassandra

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  chat-service:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - cassandra
      - redis
    environment:
      CASSANDRA_HOST: cassandra
      CASSANDRA_PORT: 9042
      REDIS_HOST: redis
      REDIS_PORT: 6379
